export const projects = [
  {
    title: "This website",
    repo: "https://github.com/MelindaSW/msw_frontend_portfolio",
    description: "My current website and portfolio.",
    url: "https://melindasportfolio.netlify.app/",
    tech: ["Vue.js 3", "Vite", "Node", "Typescript", "Css", "HTML"],
    img: "melindasportfolio.jpg",
  },
  {
    title: "Personal website",
    repo: "https://github.com/MelindaSW/melindasw.se-sourcecode",
    description:
      "My previous portfolio and personal website. Presenting both coding projects and a gallery of some of my art projects.",
    url: "https://melindasw.netlify.app/",
    tech: [
      "Vue.js 2",
      "Vue CLI",
      "Node",
      "JavaScript",
      "vue-router",
      "Vuetify",
      "HTML",
      "Sass",
    ],
    img: "melindaswse.jpg",
  },
  {
    title: "My todos",
    repo: "https://github.com/MelindaSW/todo-app-react",
    description: "A todo app created with React and react-redux. ",
    url: "https://mytodos-msw.netlify.app/",
    tech: [
      "React.js",
      "Node",
      "Typescript",
      "react-redux",
      "Vite",
      "Css",
      "HTML",
    ],
    img: "mytodos.jpg",
  },
  {
    title: "Haiku generator",
    repo: "https://github.com/MelindaSW/poetry-generator-api",
    description:
      "A haiku generator api. Can be run with maven: ./mvnw spring-boot:run. Go to http://localhost:8080/swagger-ui.html#/ and generate poetry via the endpoints",
    url: "test",
    tech: ["Java", "Spring Boot", "Maven", "Lombok", "Swagger", "REST"],
    img: "pg1.png",
  },
  {
    title: "Poetry Slack",
    repo: "https://github.com/wasse/slack-poem",
    description:
      "A full stack web applicaion for a group project at YRGO. It generates different kinds of poetry from the text content of the channels and with the help of Slacks API, the user can then choose to send it to slack.",
    url: "",
    tech: [
      "JavaScript",
      "React.js",
      "Java EE",
      "TomEE (Tomcat)",
      "REST",
      "Maven",
      "Swagger",
      "Postgresql",
      "Mobx",
      "Bulma",
      "Sass",
      "HTML",
    ],
    img: "ps2.png",
  },
  // {
  //     title: "",
  //     repo: "",
  //     description: "",
  //     url: "",
  //     tech: [""],
  //     img: ""
  // },
]
