export const projects = [
  {
    title: "Personal website",
    repo: "https://github.com/MelindaSW/melindasw.se-sourcecode",
    description: "My previous portfolio and personal website.",
    url: "https://melindasw.netlify.app/",
    tech: [
      "Vue.js 2",
      "Vue CLI",
      "Node",
      "JavaScript",
      "vue-router",
      "Vuetify",
      "Sass",
    ],
    img: "melindaswse.jpg",
  },
  {
    title: "Haiku generator",
    repo: "https://github.com/MelindaSW/poetry-generator-api",
    description:
      "A haiku generator api. Can be run with maven: ./mvnw spring-boot:run. Go to http://localhost:8080/swagger-ui.html#/ and generate poetry via the endpoints",
    url: "test",
    tech: ["Java", "Spring Boot", "Maven", "Lombok", "Swagger", "REST"],
    img: "pg1.png",
  },
  {
    title: "Poetry Slack",
    repo: "https://github.com/wasse/slack-poem",
    description:
      "This web applicaion was a school group project for the project and entreprenourship course at YRGO. It is using Slacks API and the applications own backend. Based on the content of the selected channel conversation it generates different kinds of poetry and the user can then choose to post it in the desired channel",
    url: "",
    tech: [
      "JavaScript",
      "React.js",
      "Java EE",
      "TomEE (Tomcat)",
      "REST",
      "Maven",
      "Swagger",
      "Postgresql",
      "Mobx",
      "Bulma",
      "Sass",
    ],
    img: "ps2.png",
  },
  {
    title: "Personal website",
    repo: "https://github.com/MelindaSW/melindasw.se-sourcecode",
    description: "My previous portfolio and personal website.",
    url: "https://melindasw.netlify.app/",
    tech: [
      "Vue.js 2",
      "Vue CLI",
      "Node",
      "JavaScript",
      "vue-router",
      "Vuetify",
      "Sass",
    ],
    img: "melindaswse.jpg",
  },
  {
    title: "Poetry Slack",
    repo: "https://github.com/wasse/slack-poem",
    description:
      "This web applicaion was a school group project for the project and entreprenourship course at YRGO. It is using Slacks API and the applications own backend. Based on the content of the selected channel conversation it generates different kinds of poetry and the user can then choose to post it in the desired channel",
    url: "",
    tech: [
      "JavaScript",
      "React.js",
      "Java EE",
      "TomEE (Tomcat)",
      "REST",
      "Maven",
      "Swagger",
      "Postgresql",
      "Mobx",
      "Bulma",
      "Sass",
    ],
    img: "ps2.png",
  },
  {
    title: "Personal website",
    repo: "https://github.com/MelindaSW/melindasw.se-sourcecode",
    description: "My previous portfolio and personal website.",
    url: "https://melindasw.netlify.app/",
    tech: [
      "Vue.js 2",
      "Vue CLI",
      "Node",
      "JavaScript",
      "vue-router",
      "Vuetify",
      "Sass",
    ],
    img: "melindaswse.jpg",
  },
  {
    title: "Personal website",
    repo: "https://github.com/MelindaSW/melindasw.se-sourcecode",
    description: "My previous portfolio and personal website.",
    url: "https://melindasw.netlify.app/",
    tech: [
      "Vue.js 2",
      "Vue CLI",
      "Node",
      "JavaScript",
      "vue-router",
      "Vuetify",
      "Sass",
    ],
    img: "melindaswse.jpg",
  },
  {
    title: "Haiku generator",
    repo: "https://github.com/MelindaSW/poetry-generator-api",
    description:
      "A haiku generator api. Can be run with maven: ./mvnw spring-boot:run. Go to http://localhost:8080/swagger-ui.html#/ and generate poetry via the endpoints",
    url: "test",
    tech: ["Java", "Spring Boot", "Maven", "Lombok", "Swagger", "REST"],
    img: "pg1.png",
  },
  {
    title: "Poetry Slack",
    repo: "https://github.com/wasse/slack-poem",
    description:
      "This web applicaion was a school group project for the project and entreprenourship course at YRGO. It is using Slacks API and the applications own backend. Based on the content of the selected channel conversation it generates different kinds of poetry and the user can then choose to post it in the desired channel",
    url: "",
    tech: [
      "JavaScript",
      "React.js",
      "Java EE",
      "TomEE (Tomcat)",
      "REST",
      "Maven",
      "Swagger",
      "Postgresql",
      "Mobx",
      "Bulma",
      "Sass",
    ],
    img: "ps2.png",
  },
  {
    title: "Personal website",
    repo: "https://github.com/MelindaSW/melindasw.se-sourcecode",
    description: "My previous portfolio and personal website.",
    url: "https://melindasw.netlify.app/",
    tech: [
      "Vue.js 2",
      "Vue CLI",
      "Node",
      "JavaScript",
      "vue-router",
      "Vuetify",
      "Sass",
    ],
    img: "melindaswse.jpg",
  },
  // {
  //     title: "",
  //     repo: "",
  //     description: "",
  //     url: "",
  //     tech: [""],
  //     img: ""
  // },
]
